apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume 
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/site"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
