# This is a basic workflow to help you get started with Actions

name: buid-images-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'lemp-images-ci/Dockerfile'

jobs:
  docker-build-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build images
        run: |
           cd lemp-images-ci
           docker build -t l9xhub/mariadb:latest --target img1 .
           docker build -t l9xhub/nginx:latest --target img2 .
           docker build -t l9xhub/php-fpm:latest --target img3 .

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
